name: Render and Deploy Quarto Website

on:
  push:
    branches:
      - main  # ou la branche sur laquelle ton site est hébergé
    paths:
      - "**.qmd" 
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🛠 Installer Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: 📦 Installer Pandoc et les dépendances R (si nécessaire)
        run: |
          sudo apt-get install -y pandoc
          
      - name: 🚀 Supprimer les fichiers générés précédemment
        run: rm -rf _site/*

      - name: 🔨 Générer le site avec Quarto
        run: quarto render

      - name: 🚫 Désactiver Jekyll
        run: touch _site/.nojekyll

      - name: 🚀 Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # Déploiement sur gh-pages
          force_orphan: true  # Permet de recréer proprement la branche
          
      - name: 📂 Copy Static Assets (CSS, JS, Images)
        run: cp -r styles/ _site/styles/ || true
